#!/bin/bash
eselect fontconfig disable 09-texlive.conf
eselect fontconfig disable 10-scale-bitmap-fonts.conf
eselect fontconfig disable 10-no-sub-pixel.conf
eselect fontconfig disable 10-sub-pixel-bgr.conf
eselect fontconfig disable 10-sub-pixel-vbgr.conf
eselect fontconfig disable 10-sub-pixel-vrgb.conf
eselect fontconfig disable 10-unhinted.conf
eselect fontconfig disable 11-lcdfilter-legacy.conf
eselect fontconfig disable 11-lcdfilter-light.conf
eselect fontconfig disable 20-unhint-small-dejavu-sans.conf
eselect fontconfig disable 20-unhint-small-dejavu-sans-mono.conf
eselect fontconfig disable 20-unhint-small-dejavu-serif.conf
eselect fontconfig disable 20-unhint-small-vera.conf
eselect fontconfig disable 25-unhint-nonlatin.conf
eselect fontconfig disable 57-dejavu-sans.conf
eselect fontconfig disable 57-dejavu-sans-mono.conf
eselect fontconfig disable 57-dejavu-serif.conf
eselect fontconfig disable 59-google-droid-sans.conf
eselect fontconfig disable 59-google-droid-sans-mono.conf
eselect fontconfig disable 59-google-droid-serif.conf
eselect fontconfig disable 65-khmer.conf
eselect fontconfig disable 69-unifont.conf
eselect fontconfig disable 70-no-bitmaps.conf
eselect fontconfig disable 70-yes-bitmaps.conf
eselect fontconfig enable 10-autohint.conf
eselect fontconfig enable 10-sub-pixel-rgb.conf
eselect fontconfig enable 11-lcdfilter-default.conf
eselect fontconfig enable 20-fix-globaladvance.conf
eselect fontconfig enable 30-metric-aliases.conf
eselect fontconfig enable 30-urw-aliases.conf
eselect fontconfig enable 31-cantarell.conf
eselect fontconfig enable 40-nonlatin.conf
eselect fontconfig enable 42-luxi-mono.conf
eselect fontconfig enable 45-latin.conf
eselect fontconfig enable 49-sansserif.conf
eselect fontconfig enable 50-user.conf
eselect fontconfig enable 51-local.conf
eselect fontconfig enable 57-dejavu-sans.conf
eselect fontconfig enable 57-dejavu-sans-mono.conf
eselect fontconfig enable 57-dejavu-serif.conf
eselect fontconfig enable 60-latin.conf
eselect fontconfig enable 60-liberation.conf
eselect fontconfig enable 65-fonts-persian.conf
eselect fontconfig enable 65-nonlatin.conf
eselect fontconfig enable 69-unifont.conf
eselect fontconfig enable 80-delicious.conf
eselect fontconfig enable 90-synthetic.conf
eselect fontconfig enable 99pdftoopvp.conf
