#!/bin/bash

EXE="googleit"

OVERLAY="two-overlay"

if [ ! -e /usr/local/sbin/${EXE} ] ; then
  ln -s /home/overlays/${OVERLAY}/scripts/${EXE} /usr/local/sbin/${EXE}
fi

if [ ! -h /usr/local/sbin/${EXE} ] ; then
  rm -f /usr/local/sbin/${EXE}
  ln -s /home/overlays/${OVERLAY}/scripts/${EXE} /usr/local/sbin/${EXE}
fi

if [ -e "/usr/lib/firefox/searchplugins/google.xml" ] ; then

  sed -i -e 's/www.google.com/www.google.it/' /usr/lib/firefox/searchplugins/google.xml

fi
