#!/bin/bash

EXE="preserved_libs"

OVERLAY="common-stuff"

if [ ! -e /usr/local/sbin/${EXE} ] ; then
  ln -s /usr/local/overlays/${OVERLAY}/scripts/${EXE} /usr/local/sbin/${EXE}
fi

if [ ! -h /usr/local/sbin/${EXE} ] ; then
  rm -f /usr/local/sbin/${EXE}
  ln -s /usr/local/overlays/${OVERLAY}/scripts/${EXE} /usr/local/sbin/${EXE}
fi

if [ "$1" == "do" ] ; then

  emerge -qvk @preserved-rebuild

else

  portageq list_preserved_libs /

fi
